name: 'Update release information in extension files'
description: 'Automatically update release information'
inputs:
  repository:
    description: 'Repository name'
    required: true
    default: ''
  action:
    description: 'Choose what the cation should do, initial_changelog_and_version_update, check_changlog_updated'
    required: true
    default: 'initial_changelog_and_version_update'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.action }}
